function devicechoice = chooseaudiodrivers
%devicechoice = chooseaudiodrivers
%This function create a new window to select a new audio driver when you
%are using  the 'real time' mode in the GUI of the RAZR, playrec must be
%installed on your computer to use it.
%devicechoice is the ID of the  driver you selected in the popupmenu>
%%
d = dialog('Position',[400 250 500 500],'Name','Select an Audio Driver');
devices=playrec('getDevices');
n_avbl_dvcs=size(devices,2)
name=cell(1,n_avbl_dvcs);
for i=1:n_avbl_dvcs
    name{1,i}=devices(i).name;
end
txt1 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[150 450 200 25 ],...
    'String','Select a devices.');

popup = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[150 400 200 25],...
    'String',name,...
    'Callback',@popup_callback);
txt2 = uicontrol('Parent',d,...
    'Position',[150 100 200 25 ],...
    'String','Ok',...
    'Callback','delete(gcf)');

info1=sprintf('ID:%d     hostAPI: %s',devices(1).deviceID,devices(1).hostAPI);
info2=sprintf('Input Channel: %d    Ouput Channel :%d',devices(1).inputChans,devices(1).outputChans);
info3=sprintf('High Input Latency: %d ms   Low Input Latency : %d ms',1000*devices(1).defaultHighInputLatency,1000*devices(1).defaultLowInputLatency);
info4=sprintf('High Output Latency: %d ms    Low Output Latency: %d ms',1000*devices(1).defaultHighOutputLatency,1000*devices(1).defaultLowOutputLatency);
info5=sprintf('Default Sample Rate: %d Hz',devices(1).defaultSampleRate);
txt3 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[50 350 400 25],...
    'String',info1);
txt4 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[50 300 400 25],...
    'String',info2);
txt5 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[50 250 400 25],...
    'String',info3);
txt6 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[50 200 400 25],...
    'String',info4);
txt7 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[50 150 400 25],...
    'String',info5);
uiwait(d);
return

    function popup_callback(popup,event)
        info1=sprintf('ID:%d     hostAPI: %s',devices(popup.Value).deviceID,devices(popup.Value).hostAPI);
info2=sprintf('Input Channel: %d    Ouput Channel :%d',devices(popup.Value).inputChans,devices(popup.Value).outputChans);
info3=sprintf('High Input Latency: %d ms   Low Input Latency : %d ms',1000*devices(popup.Value).defaultHighInputLatency,1000*devices(popup.Value).defaultLowInputLatency);
info4=sprintf('High Output Latency: %d ms    Low Output Latency: %d ms',1000*devices(popup.Value).defaultHighOutputLatency,1000*devices(popup.Value).defaultLowOutputLatency);
info5=sprintf('Default Sample Rate: %d Hz',devices(popup.Value).defaultSampleRate);
        set(txt3,'String',info1);
        set(txt4,'String',info2);
        set(txt5,'String',info3);
        set(txt6,'String',info4);
        set(txt7,'String',info5);
        devicechoice =popup.Value-1;
    end
end